### ISSUE TITLE
Where do you get the API key?

### ISSUE THREAD

**Issue by MadBomber** [AirspaceTechnologies/google-cloud-vision#3]
This question is above and beyond the context of your gem.  I am not a google developer.  I've followed all the instructions I can find online and have ended up with a google cloud trial account.  I have yet to find the place that says press this button to get a google cloud vision api key.  I've got all sorts of google junk now, server keys, browser keys, services keys a couple of JSON files.  Not a single key-like string will return anything other than the google error message that says its not a valid API key.

Please where is the magic google page the gives out the key needed to work with your gem?

**Comment by RyanRusnak** [comment]
Have you went here? https://console.developers.google.com/apis/. Under "credentials" you will see a section called API keys. That key is used for all of your enabled API's and is the key you need for this gem.

To enable the API in the Google console, go back to Overview instead of Credentials and search for the Google Cloud Vision API. Click enable and you are good to go! Let me know if that works.

**Comment by MadBomber** [comment]
:-)

After verifing everything was enabled ... I tried my server-to-server key
and got NO JOY.  Then it hit me, get rid of the square brackets because
they look odd.  I did and it worked.

In the readme is says:

GoogleCloudVision::Classifier.new('[YOUR_API_KEY]',

so I replace YOUR_API_KEY with my API key.

when I got rid of the square brackets things started working.

Now don't I feel silly.

On Tue, Apr 19, 2016 at 2:17 PM, Ryan <notifications@github.com> wrote:

> Have you went here? https://console.developers.google.com/apis/. Under
> "credentials" you will see a section called API keys. That key is used for
> all of your enabled API's and is the key you need for this gem.
>
> To enable the API in the Google console, go back to Overview instead of
> Credentials and search for the Google Cloud Vision API. Click enable and
> you are good to go! Let me know if that works.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/AirspaceTechnologies/google-cloud-vision/issues/3#issuecomment-212074919>
>



-- 
Dewayne
  o-*

**Comment by RyanRusnak** [comment]
Ah sorry! I should have been more clear! I will close the issue now, but thanks for opening it. Hopefully it will help other developers in the future! Good luck!
