### ISSUE TITLE
Invalid Key?

### ISSUE THREAD

**Issue by anthonyschurz** [AirspaceTechnologies/google-cloud-vision#4]
Hey Ryan,
This gem looks great and could potentially save us tons of time. We've been getting an invalid key error when we added the code mentioned in your readme even though our key is working in the google developer console. Any thoughts on what could be causing that error?

PS awesome beer cannon video :)

**Comment by RyanRusnak** [comment]
Haha you sir, are an Internet sleuth! Can you post how you are passing in the key?

**Comment by anthonyschurz** [comment]
Thanks for the quick response, Ryan! Yes, I am nothing if not an Internet sleuth. We added the following code to our user controller. Are there any gem dependencies we may be missing? We're pretty barebones right now.

def index
    @users = User.all
    @art = GoogleCloudVision::Classifier.new('[f1d12345e3c19bd376fe4923767103c85eff5d7b]',
    [{ image: './ducks.jpg', detection: 'LABEL_DETECTION', max_results: 10 }]).response
    render :index
  end

**Comment by RyanRusnak** [comment]
Nope! Looks like you are falling victim to my awful documentation. Try removing the brackets.

```
def index
  @users = User.all
  @art = GoogleCloudVision::Classifier.new('f1d12345e3c19bd376fe4923767103c85eff5d7b',
  [{ image: './ducks.jpg', detection: 'LABEL_DETECTION', max_results: 10 }]).response
  render :index
end
```

**Comment by anthonyschurz** [comment]
Got it to work! Thanks for all the help, man :) We found out my buddy's key
actually wasn't working but it worked on mine.

**Comment by RyanRusnak** [comment]
My pleasure! I am glad you find it useful!
